//
//  Registrar.h
//  Ind
//
//  Created by ryan on 14/04/2017.
//  Copyright © 2017 ryan. All rights reserved.
//
//#pragma once

#ifndef Registrar_h
#define Registrar_h

#import "ind.h"

REGISTER_IND(CInd_MA,"MA");
REGISTER_IND(CInd_KDJ,"KDJ");
REGISTER_IND(CInd_VMA,"VOL");
REGISTER_IND(CInd_MACD,"MACD");
REGISTER_IND(CInd_RSI,"RSI");
REGISTER_IND(CInd_WR, "WR");
REGISTER_IND(CInd_VR,"VR");
REGISTER_IND(CInd_DMI,"DMI");
REGISTER_IND(CInd_DMA,"DMA");
REGISTER_IND(CInd_TRIX,"TRIX");
REGISTER_IND(CInd_BRAR,"BRAR");
REGISTER_IND(CInd_CR,"CR");
//REGISTER_IND(CInd_OBV,"OBV");
//REGISTER_IND(CInd_ASI,"ASI");
REGISTER_IND(CInd_EMV,"EMV");
REGISTER_IND(CInd_CCI,"CCI");
REGISTER_IND(CInd_ROC,"ROC");
REGISTER_IND(CInd_MTM,"MTM");
REGISTER_IND(CInd_PSY,"PSY");
REGISTER_IND(CInd_SAR,"SAR");
REGISTER_IND(CInd_BOLL,"BOLL");
REGISTER_IND(CInd_SLOWKD,"SLOWKD");
REGISTER_IND(CInd_EMA,"EMA");
REGISTER_IND(CInd_ENE,"ENE");
REGISTER_IND(CInd_BIAS,"BIAS");

#endif /* Registrar_h */
